apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: consumer
    deploymentconfig: consumer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
